# Generated by Django 5.2.5 on 2025-08-12 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
